modes:
  ast: 
    fields:
      default: 
        - idListString
        - creator
        - cpxUnique
        - sourceString
        - subtreeNodes
        - childrenNodes
        - tokenNodes
        - spaceNodes
      source:
        - sourceString
        - subtreeNodes

  cpx: 
    fields:
      default: 
        - unique
        - chainListString
        - cpsCount
        - rootAstSourceString
        - cpxEdges
  
  cps:
    fields:
      default: 
        - unique
        - settledId
        - cpsEdges

  trn:
    fields:
      default: 
        - kind
        - transformClass
        - isMount
        - chainString
        - source
        - localTrnEdges
        - foreignTrnEdges

  tcpx:
    fields:
      default:
        - tCpsCount
        - tCpxEdges

  tcps:
    fields:
      default:
        - tCpsEdges

  ser:
    fields:
      default:
        - key
        - chainString
        - kind
        - source
        - children
      all:
        - key
        - chain
        - chainString
        - props
        - kind
        - source
        - children
