modes:
  ast: 
    fields:
      default: 
        - idListString
        - creator
        - cpxUnique
        - sourceString
        - subtreeNodes
        - childrenNodes
        - tokenNodes
        - spaceNodes
      source:
        - sourceString
        - subtreeNodes

  cpx: 
    fields:
      default: 
        - unique
        - chainListString
        - cpsCount
        - rootAstSourceString
        - cpxEdges
  
  cps:
    fields:
      default: 
        - unique
