import Prism from "prismjs";

import "prismjs/components/prism-markup";
import "prismjs/components/prism-markup-templating";

import "prismjs/components/prism-javascript.js";
import "prismjs/components/prism-bash.js";
import "prismjs/components/prism-awk.js";
import "prismjs/components/prism-bash.js";
import "prismjs/components/prism-csharp.js";
import "prismjs/components/prism-clike.js";
import "prismjs/components/prism-c.js";
import "prismjs/components/prism-cpp.js";
import "prismjs/components/prism-css.js";
import "prismjs/components/prism-csv.js";
import "prismjs/components/prism-docker.js";
import "prismjs/components/prism-excel-formula.js";
import "prismjs/components/prism-git.js";
import "prismjs/components/prism-go.js";
import "prismjs/components/prism-graphql.js";
import "prismjs/components/prism-handlebars.js";
import "prismjs/components/prism-http.js";
import "prismjs/components/prism-java.js";
import "prismjs/components/prism-json.js";
import "prismjs/components/prism-json5.js";
import "prismjs/components/prism-jsx.js";
import "prismjs/components/prism-less.js";
import "prismjs/components/prism-lilypond.js";
import "prismjs/components/prism-llvm.js";
import "prismjs/components/prism-matlab.js";
import "prismjs/components/prism-mermaid.js";
import "prismjs/components/prism-nginx.js";
import "prismjs/components/prism-php.js";
import "prismjs/components/prism-powershell.js";
import "prismjs/components/prism-protobuf.js";
import "prismjs/components/prism-protobuf.js";
import "prismjs/components/prism-python.js";
import "prismjs/components/prism-regex.js";
import "prismjs/components/prism-sass.js";
import "prismjs/components/prism-scss.js";
import "prismjs/components/prism-supercollider.js";
import "prismjs/components/prism-tsx.js";
import "prismjs/components/prism-vim.js";
import "prismjs/components/prism-yaml.js";

export default Prism;
