packageExtensions:
  langium@*:
    dependencies:
      "@chevrotain/regexp-to-ast": "*"
      vscode-jsonrpc: "*"
      vscode-languageserver-types: "*"
  "@opentelemetry/context-zone@2.10.0":
    dependencies:
      "@opentelemetry/api": "^1.9.1"
