import type { DqmConfigPackEntryPartial } from "@dqm/package-dqm-v2";

export const DQM_BASE_CONFIG: DqmConfigPackEntryPartial = {
  id: "pluginSelectionConfig",
  config: {
    plugins: {
      standards: [
        "render-engine:DqmStaticRenderer",
        "renderer:Debug",
        "grammar:ConstantsV2",
        "grammar:BaseV2",
        "component-set:BaseV2",
        "renderer:BaseV2",
        "component-set:FrameV2:Container",
        "grammar:FrameV2",
        "grammar:ParamsV2",
        "component-set:FrameV2:Code",
        "component-set:FrameV2:Audio",
        "component-set:FrameV2:Html",
        "renderer:HtmlPrimitives",
        "renderer:Audio",
        "renderer:Osmd",
        "renderer:Code",
        "component-set:FrameV2:Debug",
      ],
      requested: [
        "render-engine:DqmStaticRenderer",
        "renderer:Debug",
        "grammar:ConstantsV2",
        "grammar:BaseV2",
        "component-set:BaseV2",
        "renderer:BaseV2",
        "component-set:FrameV2:Container",
        "grammar:FrameV2",
        "grammar:ParamsV2",
        "component-set:FrameV2:Code",
        "component-set:FrameV2:Audio",
        "component-set:FrameV2:Html",
        "renderer:HtmlPrimitives",
        "renderer:Audio",
        "renderer:Osmd",
        "renderer:Code",
        "component-set:FrameV2:Debug",
      ],
    },
  },
};
