export const DQM_BASE_CONFIG = {
    id: "pluginSelectionConfig",
    config: {
        plugins: {
            standards: [
                "render-engine:DqmStaticRenderer",
                "renderer:Debug",
                "grammar:ConstantsV2",
                "grammar:BaseV2",
                "component-set:BaseV2",
                "renderer:BaseV2",
                "component-set:FrameV2:Container",
                "grammar:FrameV2",
                "grammar:ParamsV2",
                "component-set:FrameV2:Debug",
                "component-set:FrameV2:Code",
                "component-set:FrameV2:Audio",
                "component-set:FrameV2:Html",
                "renderer:HtmlPrimitives",
                "component-set:FrameV2:Mermaid",
                "renderer:Audio",
                "renderer:Osmd",
                "renderer:Code",
                "renderer:Mermaid",
            ],
            requested: [
                "render-engine:DqmStaticRenderer",
                "renderer:Debug",
                "grammar:ConstantsV2",
                "grammar:BaseV2",
                "component-set:BaseV2",
                "renderer:BaseV2",
                "component-set:FrameV2:Container",
                "grammar:FrameV2",
                "grammar:ParamsV2",
                "component-set:FrameV2:Debug",
                "component-set:FrameV2:Code",
                "component-set:FrameV2:Audio",
                "component-set:FrameV2:Html",
                "renderer:HtmlPrimitives",
                "component-set:FrameV2:Mermaid",
                "renderer:Audio",
                "renderer:Osmd",
                "renderer:Code",
                "renderer:Mermaid",
            ],
        },
    },
};
// config: {
//   plugins: {
//     standards: [
//       "render-engine:DqmStaticRenderer",
//       "renderer:Debug",
//       "grammar:ConstantsV2",
//       "grammar:BaseV2",
//       "component-set:BaseV2",
//       "renderer:BaseV2",
//       "component-set:FrameV2:Container",
//       "grammar:FrameV2",
//       "grammar:ParamsV2",
//       "component-set:FrameV2:Code",
//       "component-set:FrameV2:Audio",
//       "component-set:FrameV2:Html",
//       "component-set:FrameV2:Mermaid",
//       "renderer:HtmlPrimitives",
//       "renderer:Audio",
//       "renderer:Osmd",
//       "renderer:Code",
//       "component-set:FrameV2:Debug",
//     ],
//     requested: [
//       "render-engine:DqmStaticRenderer",
//       "renderer:Debug",
//       "grammar:ConstantsV2",
//       "grammar:BaseV2",
//       "component-set:BaseV2",
//       "renderer:BaseV2",
//       "component-set:FrameV2:Container",
//       "grammar:FrameV2",
//       "grammar:ParamsV2",
//       "component-set:FrameV2:Code",
//       "component-set:FrameV2:Audio",
//       "component-set:FrameV2:Html",
//       "renderer:HtmlPrimitives",
//       "renderer:Audio",
//       "renderer:Osmd",
//       "renderer:Code",
//       "component-set:FrameV2:Debug",
//     ],
//   },
// },
