/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InfoRouteImport } from './routes/info'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewGraphIndexRouteImport } from './routes/view/graph/index'
import { Route as ViewRenderDocumentIndexRouteImport } from './routes/view/render/document/index'
import { Route as ViewNodesCpxIndexRouteImport } from './routes/view/nodes/cpx/index'
import { Route as ViewNodesAstIndexRouteImport } from './routes/view/nodes/ast/index'
import { Route as ViewRenderAnkiWinIndexRouteImport } from './routes/view/render/anki/win/index'
import { Route as ViewRenderAnkiAndroidIndexRouteImport } from './routes/view/render/anki/android/index'

const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewGraphIndexRoute = ViewGraphIndexRouteImport.update({
  id: '/view/graph/',
  path: '/view/graph/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewRenderDocumentIndexRoute = ViewRenderDocumentIndexRouteImport.update({
  id: '/view/render/document/',
  path: '/view/render/document/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewNodesCpxIndexRoute = ViewNodesCpxIndexRouteImport.update({
  id: '/view/nodes/cpx/',
  path: '/view/nodes/cpx/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewNodesAstIndexRoute = ViewNodesAstIndexRouteImport.update({
  id: '/view/nodes/ast/',
  path: '/view/nodes/ast/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewRenderAnkiWinIndexRoute = ViewRenderAnkiWinIndexRouteImport.update({
  id: '/view/render/anki/win/',
  path: '/view/render/anki/win/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewRenderAnkiAndroidIndexRoute =
  ViewRenderAnkiAndroidIndexRouteImport.update({
    id: '/view/render/anki/android/',
    path: '/view/render/anki/android/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/info': typeof InfoRoute
  '/view/graph': typeof ViewGraphIndexRoute
  '/view/nodes/ast': typeof ViewNodesAstIndexRoute
  '/view/nodes/cpx': typeof ViewNodesCpxIndexRoute
  '/view/render/document': typeof ViewRenderDocumentIndexRoute
  '/view/render/anki/android': typeof ViewRenderAnkiAndroidIndexRoute
  '/view/render/anki/win': typeof ViewRenderAnkiWinIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/info': typeof InfoRoute
  '/view/graph': typeof ViewGraphIndexRoute
  '/view/nodes/ast': typeof ViewNodesAstIndexRoute
  '/view/nodes/cpx': typeof ViewNodesCpxIndexRoute
  '/view/render/document': typeof ViewRenderDocumentIndexRoute
  '/view/render/anki/android': typeof ViewRenderAnkiAndroidIndexRoute
  '/view/render/anki/win': typeof ViewRenderAnkiWinIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/info': typeof InfoRoute
  '/view/graph/': typeof ViewGraphIndexRoute
  '/view/nodes/ast/': typeof ViewNodesAstIndexRoute
  '/view/nodes/cpx/': typeof ViewNodesCpxIndexRoute
  '/view/render/document/': typeof ViewRenderDocumentIndexRoute
  '/view/render/anki/android/': typeof ViewRenderAnkiAndroidIndexRoute
  '/view/render/anki/win/': typeof ViewRenderAnkiWinIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/info'
    | '/view/graph'
    | '/view/nodes/ast'
    | '/view/nodes/cpx'
    | '/view/render/document'
    | '/view/render/anki/android'
    | '/view/render/anki/win'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/info'
    | '/view/graph'
    | '/view/nodes/ast'
    | '/view/nodes/cpx'
    | '/view/render/document'
    | '/view/render/anki/android'
    | '/view/render/anki/win'
  id:
    | '__root__'
    | '/'
    | '/info'
    | '/view/graph/'
    | '/view/nodes/ast/'
    | '/view/nodes/cpx/'
    | '/view/render/document/'
    | '/view/render/anki/android/'
    | '/view/render/anki/win/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InfoRoute: typeof InfoRoute
  ViewGraphIndexRoute: typeof ViewGraphIndexRoute
  ViewNodesAstIndexRoute: typeof ViewNodesAstIndexRoute
  ViewNodesCpxIndexRoute: typeof ViewNodesCpxIndexRoute
  ViewRenderDocumentIndexRoute: typeof ViewRenderDocumentIndexRoute
  ViewRenderAnkiAndroidIndexRoute: typeof ViewRenderAnkiAndroidIndexRoute
  ViewRenderAnkiWinIndexRoute: typeof ViewRenderAnkiWinIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/graph/': {
      id: '/view/graph/'
      path: '/view/graph'
      fullPath: '/view/graph'
      preLoaderRoute: typeof ViewGraphIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/render/document/': {
      id: '/view/render/document/'
      path: '/view/render/document'
      fullPath: '/view/render/document'
      preLoaderRoute: typeof ViewRenderDocumentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/nodes/cpx/': {
      id: '/view/nodes/cpx/'
      path: '/view/nodes/cpx'
      fullPath: '/view/nodes/cpx'
      preLoaderRoute: typeof ViewNodesCpxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/nodes/ast/': {
      id: '/view/nodes/ast/'
      path: '/view/nodes/ast'
      fullPath: '/view/nodes/ast'
      preLoaderRoute: typeof ViewNodesAstIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/render/anki/win/': {
      id: '/view/render/anki/win/'
      path: '/view/render/anki/win'
      fullPath: '/view/render/anki/win'
      preLoaderRoute: typeof ViewRenderAnkiWinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/render/anki/android/': {
      id: '/view/render/anki/android/'
      path: '/view/render/anki/android'
      fullPath: '/view/render/anki/android'
      preLoaderRoute: typeof ViewRenderAnkiAndroidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InfoRoute: InfoRoute,
  ViewGraphIndexRoute: ViewGraphIndexRoute,
  ViewNodesAstIndexRoute: ViewNodesAstIndexRoute,
  ViewNodesCpxIndexRoute: ViewNodesCpxIndexRoute,
  ViewRenderDocumentIndexRoute: ViewRenderDocumentIndexRoute,
  ViewRenderAnkiAndroidIndexRoute: ViewRenderAnkiAndroidIndexRoute,
  ViewRenderAnkiWinIndexRoute: ViewRenderAnkiWinIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
