/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InfoRouteImport } from './routes/info'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RenderDocumentIndexRouteImport } from './routes/render/document/index'
import { Route as NodesCpxIndexRouteImport } from './routes/nodes/cpx/index'
import { Route as NodesAstIndexRouteImport } from './routes/nodes/ast/index'

const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RenderDocumentIndexRoute = RenderDocumentIndexRouteImport.update({
  id: '/render/document/',
  path: '/render/document/',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesCpxIndexRoute = NodesCpxIndexRouteImport.update({
  id: '/nodes/cpx/',
  path: '/nodes/cpx/',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesAstIndexRoute = NodesAstIndexRouteImport.update({
  id: '/nodes/ast/',
  path: '/nodes/ast/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/info': typeof InfoRoute
  '/nodes/ast': typeof NodesAstIndexRoute
  '/nodes/cpx': typeof NodesCpxIndexRoute
  '/render/document': typeof RenderDocumentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/info': typeof InfoRoute
  '/nodes/ast': typeof NodesAstIndexRoute
  '/nodes/cpx': typeof NodesCpxIndexRoute
  '/render/document': typeof RenderDocumentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/info': typeof InfoRoute
  '/nodes/ast/': typeof NodesAstIndexRoute
  '/nodes/cpx/': typeof NodesCpxIndexRoute
  '/render/document/': typeof RenderDocumentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/info' | '/nodes/ast' | '/nodes/cpx' | '/render/document'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/info' | '/nodes/ast' | '/nodes/cpx' | '/render/document'
  id:
    | '__root__'
    | '/'
    | '/info'
    | '/nodes/ast/'
    | '/nodes/cpx/'
    | '/render/document/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InfoRoute: typeof InfoRoute
  NodesAstIndexRoute: typeof NodesAstIndexRoute
  NodesCpxIndexRoute: typeof NodesCpxIndexRoute
  RenderDocumentIndexRoute: typeof RenderDocumentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/render/document/': {
      id: '/render/document/'
      path: '/render/document'
      fullPath: '/render/document'
      preLoaderRoute: typeof RenderDocumentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/cpx/': {
      id: '/nodes/cpx/'
      path: '/nodes/cpx'
      fullPath: '/nodes/cpx'
      preLoaderRoute: typeof NodesCpxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/ast/': {
      id: '/nodes/ast/'
      path: '/nodes/ast'
      fullPath: '/nodes/ast'
      preLoaderRoute: typeof NodesAstIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InfoRoute: InfoRoute,
  NodesAstIndexRoute: NodesAstIndexRoute,
  NodesCpxIndexRoute: NodesCpxIndexRoute,
  RenderDocumentIndexRoute: RenderDocumentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
