/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InfoRouteImport } from './routes/info'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewRenderDocumentIndexRouteImport } from './routes/view/render/document/index'
import { Route as ViewNodesCpxIndexRouteImport } from './routes/view/nodes/cpx/index'
import { Route as ViewNodesAstIndexRouteImport } from './routes/view/nodes/ast/index'

const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewRenderDocumentIndexRoute = ViewRenderDocumentIndexRouteImport.update({
  id: '/view/render/document/',
  path: '/view/render/document/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewNodesCpxIndexRoute = ViewNodesCpxIndexRouteImport.update({
  id: '/view/nodes/cpx/',
  path: '/view/nodes/cpx/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewNodesAstIndexRoute = ViewNodesAstIndexRouteImport.update({
  id: '/view/nodes/ast/',
  path: '/view/nodes/ast/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/info': typeof InfoRoute
  '/view/nodes/ast': typeof ViewNodesAstIndexRoute
  '/view/nodes/cpx': typeof ViewNodesCpxIndexRoute
  '/view/render/document': typeof ViewRenderDocumentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/info': typeof InfoRoute
  '/view/nodes/ast': typeof ViewNodesAstIndexRoute
  '/view/nodes/cpx': typeof ViewNodesCpxIndexRoute
  '/view/render/document': typeof ViewRenderDocumentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/info': typeof InfoRoute
  '/view/nodes/ast/': typeof ViewNodesAstIndexRoute
  '/view/nodes/cpx/': typeof ViewNodesCpxIndexRoute
  '/view/render/document/': typeof ViewRenderDocumentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/info'
    | '/view/nodes/ast'
    | '/view/nodes/cpx'
    | '/view/render/document'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/info'
    | '/view/nodes/ast'
    | '/view/nodes/cpx'
    | '/view/render/document'
  id:
    | '__root__'
    | '/'
    | '/info'
    | '/view/nodes/ast/'
    | '/view/nodes/cpx/'
    | '/view/render/document/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InfoRoute: typeof InfoRoute
  ViewNodesAstIndexRoute: typeof ViewNodesAstIndexRoute
  ViewNodesCpxIndexRoute: typeof ViewNodesCpxIndexRoute
  ViewRenderDocumentIndexRoute: typeof ViewRenderDocumentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/render/document/': {
      id: '/view/render/document/'
      path: '/view/render/document'
      fullPath: '/view/render/document'
      preLoaderRoute: typeof ViewRenderDocumentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/nodes/cpx/': {
      id: '/view/nodes/cpx/'
      path: '/view/nodes/cpx'
      fullPath: '/view/nodes/cpx'
      preLoaderRoute: typeof ViewNodesCpxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/nodes/ast/': {
      id: '/view/nodes/ast/'
      path: '/view/nodes/ast'
      fullPath: '/view/nodes/ast'
      preLoaderRoute: typeof ViewNodesAstIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InfoRoute: InfoRoute,
  ViewNodesAstIndexRoute: ViewNodesAstIndexRoute,
  ViewNodesCpxIndexRoute: ViewNodesCpxIndexRoute,
  ViewRenderDocumentIndexRoute: ViewRenderDocumentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
