tags: []
plugins:
  standards:
    - RankiConstantsV2
    - RankiBaseV2
  requested: []
tokens:
  baseV2: 
    escape: "\\\\"
  frameV1:
    delimiter: ":::"
  frameV2: 
    pause: ","
    directive: "%"
    frame: ":"
  richTextV2:
    sentence:
      period: .
      question: "?"
      exclamation: "!"
    line:
      align: "$"
      heading: "#"
      small: "_"
    decoration:
      emphasis: "+"
      bold: "*"
      idiomatic: "/"
      underline: "_"
      abbreviation: "@"
  richStructureV2:
    delimiter: "~"
  paramsV2:
    separator:
      param: ","
      frame: ;
    key:
      negation: "!"
    operators:
      assign: "="
      append: +=
      remove: "-="
  richNumberV2:
    symbol:
      complex:
        - i
        - j
        - k
      infinity:
        - inf
        - INF
      pi:
        - pi
        - PI
      e:
        - e
        - E
    base: 
      hexadecimal:
        - x
        - X
      octal:
        - o
        - O
      binary:
        - b
        - B
    operator:
      negative: "-"
      positive: "+"
      minusPlus: 
        - "-+"
        - "∓"
      plusMinus:
        - "+-" 
        - "±"
      rational: "/"
    number:
      decimal: .
      group: _
