tags: []

content: 
  prefix: ""
  suffix: ""
    
stage: "ast"

plugins:
  requested: []
  config:
    RankiBaseV2: 
      tokens: 
        escape: "\\\\"
    RankiFrameV1:
      tokens: 
        delimiter: ":::"
        separator:
          param: ";"
    RankiFrameV2: 
      tokens:
        pause: ","
        left: 
          outer: "="
          inner: "["
        right:
          outer: "="
          inner: "]"
        separator: 
          param: "|"
    RankiRichTextV2:
      tokens: 
        sentence:
          period: .
          question: "?"
          exclamation: "!"
        line:
          align: "$"
          heading: "#"
          small: "_"
        decoration:
          emphasis: "+"
          bold: "*"
          idiomatic: "/"
          underline: "_"
          abbreviation: "@"
    RankiRichStructureV2:
      tokens: 
        delimiter: "~"
    RankiParamsV2:
      tokens: 
        separator:
          param: ","
        key:
          negation: "!"
          directive: "$"
        operators:
          assign: "="
          append: +=
          remove: "-="
    RankiRichNumberV2:
      tokens: 
        symbol:
          complex:
            - i
            - j
            - k
          infinity:
            - inf
            - INF
          pi:
            - pi
            - PI
          e:
            - e
            - E
        base: 
          hexadecimal:
            - x
            - X
          octal:
            - o
            - O
          binary:
            - b
            - B
        operator:
          negative: "-"
          positive: "+"
          minusPlus: 
            - "-+"
            - "∓"
          plusMinus:
            - "+-" 
            - "±"
          rational: "/"
        number:
          decimal: .
          group: _
