base: 
  # design:
  #   palette: generated-1
  # palettes:
  #   - name: generated-1
  #     hues: 
  #       red: 0
  #       orange: 30
  #       yellow: 55
  #       green: 130
  #       turquoise: 170
  #       blue: 210
  #       purple: 270
  #       magenta: 320
  #     lightness: [15, 20, 30, 60, 70, 80]
  #     saturation: 90
  flags:
    red:
      message: Questionable information
    orange:
      message: Derive more cards
    green: 
      message: Needs elaboration
    blue:
      message: Possibly outdated
    pink: 
      message: Rendering issues
    turquoise:
      message: Too extensive
    purple:
      message: Poor wording or formatting
tags:
  - exact: +r:scheme-light
    config:
      design:
        scheme: light
  - exact: +r:scheme-dark
    config:
      design:
        scheme: dark
  - exact: +r:theme-print
    config:
      design:
        theme: print
