base: 
  flags:
    red:
      message: Questionable information
    orange:
      message: Derive more cards
    green: 
      message: Needs elaboration
    blue:
      message: Possibly outdated
    pink: 
      message: Rendering issues
    turquoise:
      message: Too extensive
    purple:
      message: Poor wording or formatting
tags:
  - exact: +r:scheme-light
    config:
      design:
        scheme: light
  - exact: +r:theme-print
    config:
      design:
        theme: print
  - exact: +r:palette-custom-1
    config:
      design:
        palette: custom-1
        palettes:
          - name: custom-1
            hues:
              red: 0
              orange: 30
              yellow: 55
              green: 120
              blue: 210
              purple: 270
              magenta: 320
            lightness: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]
            saturation: 50
