# @dev
# #1 Anki media path.
# Vite will copy the bundle files to this path after every build.
# This works during watch as well.
services:
  dev:
    container_name: ranki
    # image: utkusarioglu/node-devcontainer:23-ubuntu-test-24
    # image: utkusarioglu/react-native-android-devcontainer:35-23-ubuntu-test-24
    image: utkusarioglu/react-native-android-devcontainer:36-24-ubuntu-test-27
    stdin_open: true
    init: true
    ports:
      - 5000:5000/tcp
      - 3000:3000/tcp
    volumes:
      - type: bind
        source: ..
        target: /workdir
        # #1
      - type: bind
        source: /mnt/c/Users/utkus/AppData/Roaming/Anki2/User 1/collection.media
        target: /target
